# Generated by Django 4.2.16 on 2024-11-15 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=20)),
                ('colour', models.CharField(blank=True, max_length=20, null=True)),
                ('no_of_owner', models.IntegerField(blank=True, null=True)),
                ('kms_driven', models.IntegerField(blank=True, null=True)),
                ('passing_till', models.DateField(blank=True, null=True)),
                ('insuarance_till', models.DateField(blank=True, null=True)),
                ('plate_no', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('status', models.CharField(choices=[('sale', 'For Sale'), ('buy', 'For Buy')], max_length=10)),
                ('year', models.DateField(blank=True, null=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('total_expenses', models.IntegerField(default=0)),
                ('profit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mob_no', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('p_type', models.CharField(choices=[('customer', 'Customer'), ('dealer', 'Dealer')], default='customer', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('image_URL', models.ImageField(blank=True, null=True, upload_to='')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='automobile.inventory')),
            ],
        ),
    ]
