# Generated by Django 4.2.16 on 2024-11-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='cid',
            new_name='inventory',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='cid',
        ),
        migrations.AddField(
            model_name='inventory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
