# Generated by Django 4.2.16 on 2024-11-16 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0002_rename_cid_expenses_inventory_remove_inventory_cid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='inventory',
            new_name='inventory_id',
        ),
    ]
