# Generated by Django 4.2.16 on 2024-11-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0003_rename_inventory_expenses_inventory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='total_expenses',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
