# Generated by Django 4.2.16 on 2024-11-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0004_alter_inventory_total_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
