# Generated by Django 4.2.16 on 2024-11-16 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0005_alter_expenses_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='total_expenses',
        ),
    ]
